language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install Cython --install-option="--no-cython-compile"
  - pip install -r requirements.txt
  - "sudo apt-get install mtdev-tools"
before_script:
  - "cd project"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
# command to run tests
script:
 - pytest # or py.test for Python versions 3.5 and below
 - "cd .."
 - "coverage run project/RemuCoverageTester.py"
after_success:
 - coveralls