class MessageKeys:
    index_key = "index"
    type_key = "type"
    command_key = "command"
    response_key = "responseTo"
    data_key = "data"
    params_key = "params"
    presentation_content_key = "presentation_content"
    ftp_port_key = "ftp_port"
    ftp_subpath_key = "ftp_subpath"
    sender_key = "sender"
